[project]
name = "space-calculator"
version = "0.3.0"
description = "A calculator for solid geometry implement by python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.black]
line-length = 88  # 设置行长度为 88
skip-string-normalization = true  # 跳过字符串规范化